### PR TITLE
Add byte array version of toRedisKV

### PR DESCRIPTION
**Pull request by jameshou**
Please review @udemy/data-infra.

### CODE REVIEW

**Comment by jameshou** [comment]
I'm going to go ahead with the merge.  If there are any comments, please add them and I'll fix them retroactively.

**Comment by sungjuly** [comment]
@jameshou thanks! LGTM. This repository is public, so we can ask to review @charsyam when he has time. haha
@charsyam, would you please take a look when you have time? ;) This change is just for adding method to save binary K/V using pipeline of redis.

**Comment by jameshou** [comment]
Haha!  Hilarious!  Right forgot that this was a public repo.  But yes, this is to add a method to save byte array instead of string.

**Comment by charsyam** [comment]
hi @sungjuly @jameshou I'm not an expert of Spark and Scala.
But :) LGTM!

**Pull request merged**
